//! Autogenerated weights for `pallet_supersig`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-05-19, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/parachain-collator
// benchmark
// --dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_supersig
// --extrinsic
// create_supersig
// --steps
// 20
// --repeat
// 10
// --output
// ./pallets/supersig/src/new_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
    fn create_supersig(z: u32) -> Weight;
    fn submit_call(z: u32) -> Weight;
    fn approve_call() -> Weight;
    fn remove_call() -> Weight;
    fn add_members(z: u32) -> Weight;
    fn remove_members(z: u32) -> Weight;
    fn delete_supersig() -> Weight;
    fn leave_supersig() -> Weight;
}

/// Weight functions for `pallet_supersig`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Supersig NonceSupersig (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: Supersig Members (r:3 w:3)
	// Storage: Supersig TotalMembers (r:1 w:1)
	fn create_supersig(z: u32, ) -> Weight {
		(92_124_000u64)
			// Standard Error: 300_000
			.saturating_add((5_292_000u64).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(7u64))
			.saturating_add(T::DbWeight::get().reads((1u64).saturating_mul(z as Weight)))
			.saturating_add(T::DbWeight::get().writes(7u64))
			.saturating_add(T::DbWeight::get().writes((1u64).saturating_mul(z as Weight)))
    }
	// Storage: Supersig TotalMembers (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: Supersig NonceCall (r:1 w:1)
	// Storage: Supersig Calls (r:0 w:1)
	fn submit_call(z: u32, ) -> Weight {
		(142_154_000u64)
			// Standard Error: 0
			.saturating_add((3_000u64).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(3u64))
			.saturating_add(T::DbWeight::get().writes(3u64))
	}
	// Storage: Supersig TotalMembers (r:1 w:0)
	// Storage: Supersig Members (r:1 w:0)
	// Storage: Supersig Calls (r:1 w:1)
	// Storage: Supersig UsersVotes (r:1 w:2)
	// Storage: Supersig Votes (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn approve_call() -> Weight {
		(100_966_000u64)
			.saturating_add(T::DbWeight::get().reads(6u64))
			.saturating_add(T::DbWeight::get().writes(5u64))
	}
	// Storage: Supersig TotalMembers (r:1 w:0)
	// Storage: Supersig Calls (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Supersig UsersVotes (r:0 w:1)
	// Storage: Supersig Votes (r:0 w:1)
	fn remove_call() -> Weight {
		(169_955_000u64)
			.saturating_add(T::DbWeight::get().reads(3u64))
			.saturating_add(T::DbWeight::get().writes(4u64))
	}
	// Storage: Supersig TotalMembers (r:1 w:1)
	// Storage: Supersig Members (r:3 w:3)
	// Storage: System Account (r:1 w:1)
	fn add_members(z: u32, ) -> Weight {
		(41_231_000u64)
			// Standard Error: 126_000
			.saturating_add((6_345_000u64).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(5u64))
			.saturating_add(T::DbWeight::get().reads((1u64).saturating_mul(z as Weight)))
			.saturating_add(T::DbWeight::get().writes(5u64))
			.saturating_add(T::DbWeight::get().writes((1u64).saturating_mul(z as Weight)))
	}
	// Storage: Supersig TotalMembers (r:1 w:1)
	// Storage: Supersig Members (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn remove_members(z: u32, ) -> Weight {
		(34_818_000u64)
			// Standard Error: 192_000
			.saturating_add((7_716_000u64).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(2u64))
			.saturating_add(T::DbWeight::get().reads((1u64).saturating_mul(z as Weight)))
			.saturating_add(T::DbWeight::get().writes(2u64))
			.saturating_add(T::DbWeight::get().writes((1u64).saturating_mul(z as Weight)))
	}
	// Storage: Supersig NonceSupersig (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: Supersig Supersigs (r:1 w:1)
	// Storage: Supersig NonceCall (r:0 w:1)
	fn delete_supersig() -> Weight {
		(107_739_000u64)
			.saturating_add(T::DbWeight::get().reads(4u64))
			.saturating_add(T::DbWeight::get().writes(4u64))
	}
	// Storage: Supersig TotalMembers (r:1 w:1)
	// Storage: Supersig Members (r:1 w:1)
	fn leave_supersig() -> Weight {
		(110_037_000u64)
			.saturating_add(T::DbWeight::get().reads(2u64))
			.saturating_add(T::DbWeight::get().writes(2u64))
	}
}

