//! Autogenerated weights for `pallet_supersig`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-05-19, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/parachain-collator
// benchmark
// --dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_supersig
// --extrinsic
// create_supersig
// --steps
// 20
// --repeat
// 10
// --output
// ./pallets/supersig/src/new_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
    fn create_supersig() -> Weight;
    fn submit_call(z: u32) -> Weight;
    fn approve_call() -> Weight;
    fn remove_call() -> Weight;
}

/// Weight functions for `pallet_supersig`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Supersig NonceSupersig (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: Supersig Supersigs (r:0 w:1)
	fn create_supersig() -> Weight {
		(57_023_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: Supersig NonceSupersig (r:1 w:0)
	// Storage: Supersig Supersigs (r:1 w:0)
	// Storage: Supersig NonceCall (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Supersig Calls (r:0 w:1)
	fn submit_call(z: u32, ) -> Weight {
		(47_284_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: Supersig NonceSupersig (r:1 w:0)
	// Storage: Supersig Supersigs (r:1 w:0)
	// Storage: Supersig Calls (r:1 w:0)
	// Storage: Supersig UsersVotes (r:1 w:1)
	// Storage: Supersig Votes (r:1 w:1)
	fn approve_call() -> Weight {
		(43_870_000 as Weight)
			// Standard Error: 0
			.saturating_add((3_000 as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Supersig NonceSupersig (r:1 w:0)
	// Storage: Supersig Calls (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn remove_call() -> Weight {
		(41_556_000 as Weight)
			// Standard Error: 0
			.saturating_add((3_000 as Weight))
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}

